### PR TITLE
Add support for custom highlighting options

### PR DESCRIPTION
**Pull request by ppearcy**
This should fix:
https://github.com/searchkit/searchkit/issues/94

### CODE REVIEW

**Comment by ppearcy** [comment]
Hi, anyone out there that can review / merge this? Will also take committer privileges if people are too busy or have moved on to other things. 

Thanks!

**Comment by ppearcy** [comment]
Hi All,
  I understand that it is difficult to prioritize time and that this is not a current priority. 

That being the case, can you allow me to be a committer to this project or someone else in the community that has shown interest to help get through some low hanging fruit like this? 

Open to any other ideas, too. 

No idea if this is really the case, but at the moment, it feels like this project has been abandoned by core developers. 

Thanks
Paul

**Comment by joemcelroy** [comment]
hey Paul,

Yeh i know, we feel bad. difficult however when our current client work doesn't involve Searchkit. We are working back together now (me and @ssetem) and we're looking to picking things up over the xmas break. 

Joe

**Comment by ppearcy** [comment]
That is great! And please don't feel bad, since this really is an awesome tool that has saved me and likely others tons of time :) 

Priorities shift and it is always hard to find time.

**Comment by joemcelroy** [comment]
hey @ppearcy thanks again for your PR. Lets try get this in for 1.0.0. Could you add documentation to this new feature and also not change package.json version (il sort that out on release)

Thanks!

**Comment by ppearcy** [comment]
Done. Thanks for all the recent work!

**Comment by joemcelroy** [comment]
thanks 👍 il do a new beta release now.

**Pull request merged**
