### PR TITLE
feat: added _index field to hit

### LINKED ISSUE #1252: Do you think you'll support cross index searching in the future?
Often we're doing cross index searches and then normalising the results for display. Wondering if you'd ever consider adding this?

### PR DESCRIPTION
**Pull request by alessandrojcm**
Closes #1252

### CODE REVIEW

**Comment by alessandrojcm** [comment]
Should I do something here? Tried to run tests in my local but the snapshots fail since my local ES does not have those indices.

**Comment by joemcelroy** [comment]
the functional tests run on mocks of the elasticsearch request / response, so you should be able to update the snapshots via jest.

**Comment by alessandrojcm** [comment]
Right so I've tried loading the sample data into a local ES cluster and updating the snapshots but I am running into all sorts of errors with the tests, not sure what I'm doing wrong. Could you point me on the right direction there please?

**Comment by joemcelroy** [comment]
on the following packages: packages/searchkit, packages/searchkit-api, packages/searchkit-instantsearch-client

run the task:
```
yarn test --u
```

**Comment by alessandrojcm** [comment]
> on the following packages: packages/searchkit, packages/searchkit-api, packages/searchkit-instantsearch-client
> 
> run the task:
> 
> ```
> yarn test --u
> ```

Yes I've done that, but the tests try to connect to an ES cluster with an specific set of indices so they fail.

**Comment by joemcelroy** [comment]
the functional tests calls should be mocked (https://github.com/searchkit/searchkit/blob/main/packages/searchkit/src/___tests___/functional/KNNSearch.test.ts#L25) so it should be as simple as running it and updating the snapshots. LMK if you still cant do it and il take a look.

**Comment by alessandrojcm** [comment]
> the functional tests calls should be mocked (https://github.com/searchkit/searchkit/blob/main/packages/searchkit/src/___tests___/functional/KNNSearch.test.ts#L25) so it should be as simple as running it and updating the snapshots. LMK if you still cant do it and il take a look.

Yes if you could please take a look that'll be great, not sure what I'm doing wrong but the mocks don't seem to work correctly for some reason.

**Comment by joemcelroy** [comment]
opened here as dont have permission to push to your fork https://github.com/searchkit/searchkit/pull/1289

**Pull request closed without merging**
