### PR TITLE
Update definitions for array declaration in props.

### PR DESCRIPTION
**Pull request by richtera**
Added pull request just in case since I had the code changes locally. Hope this is good.

### CODE REVIEW

**Comment by richtera** [comment]
Ref #626

**Comment by richtera** [comment]
FYI: I noticed a bunch of updates inside of package-lock.json but didn't check those in as part of the pull request.

**Comment by richtera** [comment]
Sorry I had the wrong emails in my commit. Fixed it.

**Comment by joemcelroy** [comment]
thanks this looks good.

**Pull request merged**
