### PR TITLE
Update @types/react 0.0.0 -> 16.0.5

### PR DESCRIPTION
**Pull request by chrisfinch**
Update to the latest version of react types as old version is causing typescript errors.

See: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/13834

### CODE REVIEW

**Comment by chrisfinch** [comment]
Quick update here - it would be really helpful to get this merged

As the version of the react type defs being used currently (`0.0.0`) I've been getting a lot of typescript issues in my project where the searchkit react type defs are clashing with those installed for my project.

As a consequence I've had to use npm's shrinkwrap functionality to override the version of the type defs used for the searchkit package as below:

Overriding `0.0.0` -> `15.6.1`

```json
{
  "dependencies": {
    "searchkit": {
      "version": "2.2.1-0",
      "from": "searchkit@2.2.1-0",
      "dependencies": {
        "@types/react": {
          "version": "15.6.1",
          "from": "@types/react@0.0.0"
        }
      }
    }
  }
}
```

**Comment by joemcelroy** [comment]
i can have a quick look at this tonight but our tests are failing. Probably because its at 16.

**Comment by chrisfinch** [comment]
@joemcelroy thanks - I only went to 16.0.5 as it was the latest at the time - could also go to 15.x.x - just anything other than 0.0.0 as it seems buggy!

**Comment by chrisfinch** [comment]
For anyone who finds the PR and is having the same issue - the following changeset to tsconfig.json resolves the problem without needing to use npm-shrinkwrap:

```
+    "baseUrl": ".",
 +    "paths": {
 +      "react": ["node_modules/@types/react"]
 +    }
```

**Comment by ssetem** [comment]
going to close this, as updated on another PR

**Comment by chrisfinch** [comment]
👍

**Pull request closed without merging**
