### PR TITLE
Issue 24: Date range filter

### PR DESCRIPTION
**Pull request by MarttiR**
This adds a date range filter to enable searching of date ranges by start date and an optional end date.

Applies to #24 and #309.

Working filter, accessor, query and calendar-datepicker components are provided, albeit with a slightly tangy aftertaste of **no test coverage**.

Also supplied is a new test app for the calendar, along with some real-world open-source (ND)JSON event data. There are docs in the README on how to feed the data to an Elasticsearch instance in a Docker container, so anyone can rapidly pick up where I left off.

The filter should be usable as well with data that only has a single date field, just set the same field as both `fromDateField` and `toDateField`. Note, however, that doing so still doesn't compare the fields to the exact same datetime, but accounts for start-of-day and end-of-day to "find" all events that happen on that day.

The code was originally published at https://github.com/City-of-Turku/kada-elastic-events.

Work on date range filtering was done by @MarttiR of @avoltusfi as a part of the Turku Calendar 2.0 project for the City of Turku, Finland (@City-of-Turku).

Much needed stepping stones were laid by @GregoryPotdevin in https://github.com/GregoryPotdevin/searchkit-daterangefilter.

### CODE REVIEW

**Comment by joemcelroy** [comment]
Excellent! Il take a look at it soon. Thanks

**Comment by timmetj** [comment]
Any news to merge this? :) Looking forward for this option, maybe add an extra option for a datepicker instead of 2 input fields would be nice!

**Comment by joemcelroy** [comment]
So whats stopping this being merged is we are looking into lerna (https://github.com/lerna/lerna) so that we manage multiple packages from a single repository. We want to keep searchkit small and you add the searchkit component packages you need to i.e date filter, histogram filter, graph render, geo filter render components.

For now the main contributor can create a seperate repo for this component so others can use until then.

**Comment by timmetj** [comment]
Ok Thanks! Packages would indeed be a nice solution. Maybe @MarttiR can make a repo for now then.

**Comment by s-corley** [comment]
package for this would be awesome

**Comment by MarttiR** [comment]
@timmetj Check out the test app, it does have a working datepicker out-of-the-box!

I'll see about creating a separate package for the component(s). There's some work involved for it to be maintainable and I'm a bit starved for resources right now, so it might take until next week.

**Comment by timmetj** [comment]
Thanks, by your test app you mean https://github.com/City-of-Turku/kada-elastic-events/tree/master/src/kadasearch ?
I'll have a look at that one.
A can live with that extra week :p Thanks for your effort!

**Comment by MarttiR** [comment]
@timmetj Sorry, I should have been more explicit. It's this one: https://github.com/MarttiR/searchkit/tree/date-range-filtering/test/e2e/server/apps/calendar-app

**Comment by s-corley** [comment]
@MarttiR yes, thanks for working on this!

**Comment by MarttiR** [comment]
A package is now available in npm: `npm install --save-dev searchkit-datefilter`. 

Pull requests are welcome!

https://www.npmjs.com/package/searchkit-datefilter
https://github.com/MarttiR/searchkit-datefilter

**Comment by timmetj** [comment]
Great thanks man! Will look into this soon. Busy on new project atm. We need it to search for events, but these events can also have periods instead of 1 date, hope we can make this work with your package, not sure how to make a custom query yet in searchkit/react to ES since it needs to search for the given date in multiple fields and not just 1 :)

**Comment by s-corley** [comment]
@MarttiR I'm using the date filter and it's awesome. Could you please show me very quickly how you would use the rangeFormatter to change the display from dd.mm.yyyy to mm/dd/yyyy. Or would I have to mess around with the package? Thanks again

**Comment by ssetem** [comment]
Hey @MarttiR 

Thanks again for this component, we really appreciate it.

We have been reorganising the searchkit repo into a mono repo like react, angular, jest etc does  to allow for custom components like this.
I will try to pull in your component into our project very soon.

Thanks!

**Comment by tienthanhdhcn** [comment]
Hello, 

Date range filter is really important. Is there any update on this feature?

**Comment by joemcelroy** [comment]
Hi there, thank you for contributing but im closing this PR because its old now and has conflicts. Feel free to open a new one if you still want to add the feature! thanks

**Pull request closed without merging**
