### PR TITLE
minor documentation update for SearchkitManager

### PR DESCRIPTION
**Pull request by olf**
timeout and withCredentials parameters

### CODE REVIEW

**Comment by joemcelroy** [comment]
thanks!

**Comment by devssh** [comment]
Can you document how to change the timeout from 5000 ms?

**Comment by olf** [comment]
This would set it to 10000ms:

this.searchkit = new SearchkitManager('localhost:9200/movies', { timeout: 10000 });

**Comment by joemcelroy** [comment]
hey @devssh you can pass timeout in the `searchkitManager` options. its documented [here](http://docs.searchkit.co/stable/core/SearchkitManager.html) although not super obvious as its position is incorrect and within the [SearchkitManager options type](https://github.com/searchkit/searchkit/blob/develop/packages/searchkit/src/core/SearchkitManager.ts#L27)

**Comment by joemcelroy** [comment]
thanks @olf!

**Comment by devssh** [comment]
I added this 
`import {AxiosESTransport} from 'searchkit'`
`AxiosESTransport.timeout = 20000`

Let me check your suggestion olf!
Thanks!

**Comment by olf** [comment]
@joemcelroy It's a bit clearer in the v2.3.0 docs. Maybe it'd be worth updating the docs site with the latest docs?

**Pull request merged**
