### PR TITLE
Issue 321: Scroll to any element when hits change

### LINKED ISSUE #321: Request: scrollTo every element instead of body
If you use the scrollTo, this will only work when selecting the body, since you most only scroll a body in a webpage.
This would be better to really scroll to the given elements top.
Now it doesn't work if you select a #main div for example, you want it to go and sroll back to the top of #main but the scrolltop always is 0 because the webpage is scrolling a body.

Would look something like in HitsAccessor.js:

```
HitsAccessor.prototype.scrollIfNeeded = function () {
    if (this.searchkit.hasHitsChanged()) {
        if (this.options.scrollTo) {
            var topPos = document.querySelector(this.getScrollSelector()).offsetTop;
            document.querySelector('body').scrollTop = topPos-10;
        }
    }
};
```

### PR DESCRIPTION
**Pull request by MarttiR**
This PR makes it possible to use any query selector in the `scrollTo` prop of the `Hits` component. When results change, `body` is scrolled to the top of that element.

For example:

```jsx
<Hits
  scrollTo=".sk-layout__body"
/>
```

The code was originally published [here](https://github.com/City-of-Turku/kada-elastic-events/blob/master/src/kadasearch/HitsScrollingPatch.ts).

Closes #321.

### CODE REVIEW

**Comment by joemcelroy** [comment]
i think what we need here is a way of you providing your own scroll function so others can add their own custom scroll interaction easily. For example: `<Hits scrollTo={fn} />`. Later we could pass in source of action (change aggregations, change of query, change pagination, change sorting) aswell.

**Comment by MarttiR** [comment]
scrollTo now accepts Function as well, and in that case leaves scrolling entirely up to the user.

Example:

```
scrollTo={() => {
  document.body.scrollTop = 100;
}}
```

**Comment by timmetj** [comment]
added extra code for IE support, see https://github.com/searchkit/searchkit/issues/321#issuecomment-318633060

**Comment by Kubitomakita** [comment]
Any chance to get this merged?

**Comment by joemcelroy** [comment]
Hi there, thank you for contributing but im closing this PR because its old now and has conflicts. Feel free to open a new one if you still want to add the feature! thanks

**Pull request closed without merging**
