### PR TITLE
Documentation 0.5

### PR DESCRIPTION
**Pull request by joemcelroy**

### CODE REVIEW

**Comment by GregoryPotdevin** [comment]
InitialLoader example code uses `this.bemBlocks`. Shouldn't that be `this.props.bemBlocks` ?

**Comment by joemcelroy** [comment]
thanks il clean that up

**Comment by GregoryPotdevin** [comment]
> If you want to tweak the markup for a menu option, you can use the `itemComponent` prop and pass in a new **functional component** to be used to render each option.

Actually it works for all components, not just functional components. Change that to "pass in a component to be used..." ?

**Comment by joemcelroy** [comment]
yeh ill do a quick search. I thought i replaced them all with react

**Pull request merged**
