### PR TITLE
RangeFilter to support Histogram=false option 

### PR DESCRIPTION
**Pull request by joemcelroy**
fix for #199

### CODE REVIEW

**Comment by GregoryPotdevin** [comment]
Not sure this is valid :
```
if (this.options.loadHistogram) {
	return this.getBuckets().length == 0
}
```
Don't you always have buckets filled with zeros with the current code ? The previous code tested for the existence of 1 bucket with more than 0 entries.

**Comment by joemcelroy** [comment]
The bucket is loaded with segments which have results right? So if the bucket is empty, there are no results across the range. In that case, we need add disable class to the filter.

**Comment by GregoryPotdevin** [comment]
The accessor is using "extended_bounds", so it'll generate buckets regardless of the number of results.
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-histogram-aggregation.html#search-aggregations-bucket-histogram-aggregation-extended-bounds

also checked it on the demo's network queries :
image

This actually means that even if you specify a range of like 0-10, and if some values are outside the range, that could break the histogram's rendering. But that's another (minor) issue ^^

**Comment by joemcelroy** [comment]
yep good spot. I assumed histogram segments aren't brought back when value is 0. Il do what you did and use maxValue.

**Pull request merged**
