### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by kud**

### CODE REVIEW

**Comment by ssetem** [comment]
thanks @kud 
will look into our CI issues and then merge

**Comment by kud** [comment]
I'm on the right branch? Because first I was looking into `gh-pages` and the folder 2.0.0.

The doc is generated from the master, that's it?

**Comment by ssetem** [comment]
doc is generated from current dev branch

**Comment by kud** [comment]
Oh, so maybe I should do it from "develop" so, instead of "master"?

**Comment by ssetem** [comment]
yeah, thanks @kud

**Pull request closed without merging**
