### PR TITLE
Beta Release

### PR DESCRIPTION
**Pull request by joemcelroy**
- update to react 15 + updated units to pass from changes to way react renders to DOM for null components and text interpolation span wrappers 
- use yarn for dependency management
- update typescript to 2.1
- update ui component dependency like ui-slider

### CODE REVIEW

**Comment by thomasmodeneis** [comment]
this will fix https://github.com/searchkit/searchkit/issues/354

**Comment by joemcelroy** [comment]
released a beta version of searchkit 1.0 and is available on npm `searchkit@1.0.0-0`. This is a beta release, some tests are failing and i expect problems but at least youll be able to use all the latest goodies without issues.

We are actually using this beta release inhouse now for an experimental project so hopefully we able to spot issues quickly.

Joe

**Comment by sadovnychyi** [comment]
Possible regression in pagination (due to lodash update?).

```javascript
get(this.getResults(), ".hits.total", 1)
```

You will always get default value here because of the dot as a prefix. This one works correctly:
```javascript
get(this.getResults(), "hits.total", 1)
```

https://github.com/searchkit/searchkit/blob/develop/src/components/search/pagination/src/Pagination.tsx#L81

**Comment by aliceriot** [comment]
@sadovnychyi can confirm that there is a bug with pagination in the current `@latest` release - we ran into it and ended up patching the `<Pagination />` component to fix it.

Our fix is here:

https://github.com/mitodl/micromasters/pull/2337/files

**Comment by sadovnychyi** [comment]
@aliceriot Yep, I actually have most of components I use patched in this way, good thing it's easy with React :)

**Comment by joemcelroy** [comment]
thanks all. il sort this out for next beta release.

**Pull request merged**
