### PR TITLE
don't pin lodash to avoid duplicates

### PR DESCRIPTION
**Pull request by vincentfretin**
Don't pin lodash to remove duplicate lodash version and to be able to use only one updated version of lodash in my project instead of two.

### CODE REVIEW

**Comment by vincentfretin** [comment]
FYI lodash 4.17.4 reports security vulnerabilities.
If you're using yarn you can add to your package.json the following:
```
  "resolutions": {
    "searchkit/lodash": "^4.17.11"
  },
```
to force using a more recent lodash version.

**Comment by pahan35** [comment]
I constantly got notification about vulnerabilities in my project due to pinned lodash.

@joemcelroy could you please apply this PR and publish it?

**Comment by joemcelroy** [comment]
Sorry for delay. Ok il merge and auto release on an alpha version. Could you verify everything ok here?

**Comment by joemcelroy** [comment]
now on 2.3.1-alpha.9

**Comment by pahan35** [comment]
@joemcelroy tnx. Now the warning is gone.

Formerly I got **2.3.2** but now it is **2.3.1-alpha.9**. Will you publish as a part of stable release?

**Comment by joemcelroy** [comment]
Great, I will do, report any issues on alpha build. If I dont hear back il publish 2.3.3. 

Thanks!

**Comment by benjamingrobertson** [comment]
Any chance we could get this in a stable release @joemcelroy? Thanks!

**Pull request merged**
