### PR TITLE
Issue 327 - MenuFilter.bucketsTransform fix

### LINKED ISSUE #327: Pb with bucketsTransform props on MenuFilter
Hi,
I want to use the "bucketsTransform" props of the MenuFilter.
When i use it nothing happens, here's my code :

`<MenuFilter field="languages.raw" title="Languages" id="languages" bucketsTransform={((buckets)=> console.log(buckets))}/>`

### PR DESCRIPTION
**Pull request by bcruddy**
- Use `super.getItems()` instead of `this.accessor.getBuckets()` to get MenuFilter items
- Spacing cleanup

Fixes #327, @GregoryPotdevin's fix seemed to do the trick without changing any tests.

NOTE: the `all` bucket isn't included in the array passed to the transform method

### CODE REVIEW

**Comment by bcruddy** [comment]
@joemcelroy is this something that can be merged or do I need to monkey patch it for my use case?

**Comment by joemcelroy** [comment]
thanks! Sorry took a while to merge. Il do a release soon.

**Comment by joemcelroy** [comment]
Thanks @bcruddy just released v2.0.1

**Comment by bcruddy** [comment]
@joemcelroy thanks!

**Pull request merged**
