### PR TITLE
Issue 443: Replace React.PropTypes with prop-types package

### LINKED ISSUE #443: PropTypes in React 15.5
I left a comment in #354 yesterday, I'm hoping this gets more visibility.

I'm getting the following warning when running tests in my project with jest 19 (React 15.5.4, node 6.10.1, yarn 0.23.2):

`Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

This isn't urgent as `React.PropTypes` won't be removed until React 16 but seeing all of these warnings is driving me a bit crazy. I'd be happy to put up a fix if this isn't currently being addressed. I put together two gists of every instance of `React.PropTypes` in [`master`](https://gist.github.com/bcruddy/bbdeb094da43ab8e5835e92ff5976010) and [`develop`](https://gist.github.com/bcruddy/71a00e2b53f2a0685a4b19ec193e581e) (they appear to be the same).

I'll need to get approval at work to put up the PR which could take 2-3 days so the sooner I know if I should fix it I can start that process.

Thanks for the awesome library!

### PR DESCRIPTION
**Pull request by bcruddy**
Fixes #443

* Swap out `React.PropTypes` for the standalone `prop-types` package
* Added `.nvmrc` file

The only potential issue I see is the removal of the test in `src/__test__/core/react/SearchkitComponentSpec.tsx` - PropTypes can no longer be called directly https://facebook.github.io/react/warnings/dont-call-proptypes.html#dont-call-proptypes-directly

### CODE REVIEW

**Comment by joemcelroy** [comment]
Thanks for this! Once CLA been signed and tests pass, ill merge.

**Comment by bcruddy** [comment]
Hey @joemcelroy, I didn't catch the CLA before I got approval from legal at work. Hopefully they get to it today but it may be later in the week.

**Comment by bcruddy** [comment]
@joemcelroy just got approval and signed the CLA

**Comment by bcruddy** [comment]
@joemcelroy is there something I need to do to kick off the CircleCI tests?

**Comment by ssetem** [comment]
Just tweaked a setting on our circleci, would you mind doing a small commit that doesn't affect anything to try to retrigger, again thanks for this PR :)

**Comment by bcruddy** [comment]
@ssetem I'm happy to contribute. The tests just passed, thanks for an awesome library!

**Comment by ssetem** [comment]
thanks!!

**Comment by bcruddy** [comment]
@joemcelroy @ssetem any idea when this change will be published?

**Comment by joemcelroy** [comment]
Going to push an RC very soon, maybe today or tomorrow!

**Comment by bcruddy** [comment]
@joemcelroy awesome, I'll keep an eye out - thanks!

**Comment by joemcelroy** [comment]
@bcruddy now available on 2.0.0-10.

Thanks!

**Comment by bcruddy** [comment]
It looks like I missed a few, putting up another PR shortly

**Comment by bcruddy** [comment]
Just opened #453

**Pull request merged**
